name: p

on:
  push:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 0
        run: curl -fsSL https://tailscale.com/install.sh | sh
        
      - name: 1
        run: sudo tailscale up --authkey=${{ secrets.AUTH }} --ssh
      - name: 2
        run: sudo tailscale ip -4


      - name: 3
        run: sudo apt update

      - name: 4
        run: |
          sudo apt install -y lxqt sddm tigervnc-standalone-server tigervnc-common python3-pip
          pip install gdown
          gdown --fuzzy https://drive.google.com/file/d/1dc_4x9CdvTDvNgO12kJ4_EkXyMuky39Z/view?usp=drivesdk # lxqt
          

      - name: 5
        run: |
          IP=$(sudo tailscale ip -4)
          ssh -L 5901:localhost:5901 runner@${IP}
          sleep 22000
        
