name: pl

on:
  push:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 0
        run: curl -fsSL https://tailscale.com/install.sh | sh
        
      - name: 1
        run: sudo tailscale up --authkey=${{ secrets.AUTH }} --ssh
      - name: 2
        run: sudo tailscale ip -4


      - name: 3
        run: sudo apt update

      - name: 4
        run: |
          sudo apt install -y lxqt sddm tigervnc-standalone-server tigervnc-common python3-pip wget
          cat > lxqt.sh <<'EOF'
      
          
          mkdir -p ~/.vnc
          
          cat > ~/.vnc/xstartup <<'EOL'
     
          unset SESSION_MANAGER
          unset DBUS_SESSION_BUS_ADDRESS
          exec startlxqt
          EOL
          
          chmod +x ~/.vnc/xstartup
          
          echo "=== Set password VNC ==="
          echo "apalah" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          
          echo "=== Kill old session ==="
          vncserver -kill :1 2>/dev/null || true
          
          echo "=== Start VNC server ==="
          vncserver :1 -geometry 1280x720 -depth 24 -SecurityTypes None
          EOF
          chmod +x lxqt.sh
          
          #wget "https://drive.google.com/uc?export=download&id=1dc_4x9CdvTDvNgO12kJ4_EkXyMuky39Z" -O lxqt.sh

      - name: 5
        run: |
          IP=$(sudo tailscale ip -4)
          echo "ssh -L 5901:localhost:5901 runner@${IP}"
          sleep 22000
        
