name: CI Test

on:
  push:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: curl -fsSL https://tailscale.com/install.sh | sh
        
        
